// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/BauhausRestaurantIndex-05IqKA/App.tsx": () => import("../components/mockups/templates/BauhausRestaurantIndex-05IqKA/App.tsx"),
  "./components/mockups/templates/BauhausRestaurantIndex-OFwmAN/App.tsx": () => import("../components/mockups/templates/BauhausRestaurantIndex-OFwmAN/App.tsx"),
  "./components/mockups/templates/BauhausRestaurantIndex-VLJn2_/App.tsx": () => import("../components/mockups/templates/BauhausRestaurantIndex-VLJn2_/App.tsx"),
  "./components/mockups/templates/BauhausRestaurantIndex-Vrdh_B/App.tsx": () => import("../components/mockups/templates/BauhausRestaurantIndex-Vrdh_B/App.tsx")
};
